name: Build UI module
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODULE_NAME: stripes-reshare
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        yarn config set @folio:registry https://repository.folio.org/repository/npm-folio/
        yarn global add @folio/stripes-cli 
    - run: yarn install 
    - run: mkdir -p artifacts/md
    - run: stripes mod descriptor --full --strict 
    - run: stripes mod descriptor --full --strict | jq '.[]' > artifacts/md/$MODULE_NAME.json
    - run: cat artifacts/md/$MODULE_NAME.json
    - run: >
        curl -X POST 
        -H "Content-type: application/json"
        -d @artifacts/md/$MODULE_NAME.json
        -u registryadmin:${{ secrets.REGISTRY_ADMIN_PASS }}
        https://registry.reshare-dev.indexdata.com/_/proxy/modules
    #- run: npm publish --access public
    #  env:
    #    NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
